# Generated by Django 5.2.8 on 2025-11-29 01:12

import django.db.models.deletion
import django.db.models.manager
import src.apps.posts.enums
import src.utils.upload_file
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'db_table': 'keywords',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'db_table': 'owners',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Identifier')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO')], null=True, verbose_name='Type')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=src.apps.posts.enums.PostStatus['PENDING'], null=True, verbose_name='Status')),
                ('thumbnail', models.FileField(null=True, upload_to=src.utils.upload_file.path_and_rename_thumbnail, verbose_name='Thumbnail')),
                ('media', models.FileField(null=True, upload_to=src.utils.upload_file.path_and_rename_media, verbose_name='Media')),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Provider')),
                ('external_link', models.URLField(null=True, verbose_name='External Link')),
                ('metadata', models.JSONField(null=True)),
                ('keywords', models.ManyToManyField(related_name='posts', to='posts.keywords')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.owners', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('LAUGH', 'LAUGH'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY'), ('INSIGHTFUL', 'INSIGHTFUL')], max_length=255, verbose_name='Reaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.posts', verbose_name='Post')),
                ('user', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='users.users', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'db_table': 'reactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['created_at'], name='posts_created_060265_idx'),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['type'], name='posts_type_97ace5_idx'),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=models.Index(fields=['status'], name='posts_status_bd5975_idx'),
        ),
        migrations.AddIndex(
            model_name='reactions',
            index=models.Index(fields=['type'], name='reactions_type_872bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='reactions',
            index=models.Index(fields=['created_at'], name='reactions_created_4b8825_idx'),
        ),
    ]
