# Generated by Django 5.2.8 on 2025-11-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('LIKE', 'LIKE'), ('LOVE', 'LOVE'), ('LAUGH', 'LAUGH'), ('WOW', 'WOW'), ('SAD', 'SAD'), ('ANGRY', 'ANGRY'), ('INSIGHTFUL', 'INSIGHTFUL')], max_length=255, verbose_name='Reaction Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.posts', verbose_name='Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='users.users', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'db_table': 'reactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type'], name='reactions_type_872bdc_idx'), models.Index(fields=['created_at'], name='reactions_created_4b8825_idx')],
            },
        ),
    ]
