# Generated by Django 5.2.8 on 2025-11-28 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_reactions'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='post',
            field=models.ForeignKey(db_column='post_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.posts', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='users.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='post',
            field=models.ForeignKey(db_column='post_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.posts', verbose_name='Post'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.users', verbose_name='User'),
        ),
    ]
