# Generated by Django 5.2.8 on 2025-11-30 21:46

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_vector_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name='posts',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='post_embedding_ivfflat', opclasses=['vector_cosine_ops']),
        ),
    ]
