# Generated by Django 5.2.8 on 2025-12-01 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_posts_embedding_posts_post_embedding_ivfflat'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ForeignKey(db_column='user_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='users.users', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='owner',
            field=models.ForeignKey(db_column='owner_uuid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.owners', verbose_name='Owner'),
        ),
    ]
