# Generated by Django 5.2.8 on 2025-12-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_posts_user_alter_posts_owner"),
        ("users", "0004_users_preferences_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts",
            name="slug",
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="reactions",
            name="type",
            field=models.CharField(
                choices=[
                    ("LIKE", "LIKE"),
                    ("DISLIKE", "DISLIKE"),
                    ("LOVE", "LOVE"),
                    ("LAUGH", "LAUGH"),
                    ("WOW", "WOW"),
                    ("SAD", "SAD"),
                    ("ANGRY", "ANGRY"),
                    ("INSIGHTFUL", "INSIGHTFUL"),
                ],
                max_length=255,
                verbose_name="Reaction Type",
            ),
        ),
    ]
