# Generated by Django 5.2.8 on 2025-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
