# Generated by Django 5.2.8 on 2025-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Avatar URL'),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email'),
        ),
    ]
