# Generated by Django 5.2.8 on 2025-12-09 01:39

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_avatar_url_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='preferences_embedding',
            field=pgvector.django.vector.VectorField(dimensions=1536, null=True),
        ),
    ]
