# Generated by Django 5.2.7 on 2025-11-24 23:23

import uuid

import django.db.models.manager
from django.db import migrations, models

import src.apps.memes.enums


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Memes",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique Identifier",
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="Description")),
                (
                    "type",
                    models.IntegerField(
                        choices=[(1, "IMAGE"), (2, "GIF"), (3, "VIDEO")],
                        default=src.apps.memes.enums.MemeType["IMAGE"],
                        verbose_name="Operation Type",
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "PENDING"), (2, "APPROVED"), (3, "REJECTED")],
                        default=src.apps.memes.enums.MemeStatus["PENDING"],
                        verbose_name="Status",
                    ),
                ),
                ("url", models.URLField(null=True, verbose_name="Receipt URL")),
                ("metadata", models.JSONField(null=True)),
            ],
            options={
                "verbose_name": "Meme",
                "verbose_name_plural": "Memes",
                "db_table": "memes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="memes_created_e9832b_idx"),
                    models.Index(fields=["type"], name="memes_type_170afd_idx"),
                    models.Index(fields=["status"], name="memes_status_b3f66f_idx"),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
