# Generated by Django 5.2.7 on 2025-11-25 00:01

from django.db import migrations, models

import src.apps.memes.enums


class Migration(migrations.Migration):
    dependencies = [
        ("memes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="memes",
            name="url",
        ),
        migrations.AddField(
            model_name="memes",
            name="external_link",
            field=models.URLField(null=True, verbose_name="External Link"),
        ),
        migrations.AddField(
            model_name="memes",
            name="file",
            field=models.FileField(null=True, upload_to="", verbose_name="File"),
        ),
        migrations.AddField(
            model_name="memes",
            name="title",
            field=models.CharField(max_length=255, null=True, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="memes",
            name="description",
            field=models.TextField(null=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="memes",
            name="status",
            field=models.IntegerField(
                choices=[(1, "PENDING"), (2, "APPROVED"), (3, "REJECTED")],
                default=src.apps.memes.enums.MemeStatus["PENDING"],
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="memes",
            name="type",
            field=models.IntegerField(
                choices=[(1, "IMAGE"), (2, "GIF"), (3, "VIDEO")],
                default=src.apps.memes.enums.MemeType["IMAGE"],
                null=True,
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="memes",
            name="keywords",
            field=models.ManyToManyField(null=True, related_name="memes", to="memes.keyword"),
        ),
    ]
