# Generated by Django 5.2.7 on 2025-11-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memes", "0002_keyword_remove_memes_url_memes_external_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memes",
            name="keywords",
            field=models.ManyToManyField(related_name="memes", to="memes.keyword"),
        ),
    ]
