# Generated by Django 5.2.7 on 2025-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_alter_memes_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='memes',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='', verbose_name='Thumbnail'),
        ),
    ]
