# Generated by Django 5.2.7 on 2025-11-25 23:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0004_memes_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('username', models.CharField(max_length=255, verbose_name='Username')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
            ],
            options={
                'ordering': ['username'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='memes',
            name='provider',
            field=models.CharField(max_length=255, null=True, verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='memes',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='memes.owner', verbose_name='Owner'),
        ),
    ]
