# Generated by Django 5.2.7 on 2025-11-26 23:25

import src.utils.upload_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0005_owner_memes_provider_memes_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='file',
        ),
        migrations.AddField(
            model_name='memes',
            name='media',
            field=models.FileField(null=True, upload_to=src.utils.upload_file.path_and_rename_media, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='memes',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=src.utils.upload_file.path_and_rename_thumbnail, verbose_name='Thumbnail'),
        ),
    ]
