# Generated by Django 5.2.8 on 2025-11-29 01:12

import django.db.models.deletion
import src.apps.reports.enums
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Unique Identifier')),
                ('reason', models.CharField(choices=[('SIMPLY_DISLIKED', 'SIMPLY_DISLIKED'), ('BULLYING_OR_UNWANTED_CONTACT', 'BULLYING_OR_UNWANTED_CONTACT'), ('SUICIDE_SELF_HARM_OR_EATING_DISORDERS', 'SUICIDE_SELF_HARM_OR_EATING_DISORDERS'), ('VIOLENCE_HATE_OR_EXPLOITATION', 'VIOLENCE_HATE_OR_EXPLOITATION'), ('SALE_OR_PROMOTION_OF_RESTRICTED_ITEMS', 'SALE_OR_PROMOTION_OF_RESTRICTED_ITEMS'), ('NUDITY_OR_SEXUAL_ACTIVITY', 'NUDITY_OR_SEXUAL_ACTIVITY'), ('SCAM_FRAUD_OR_SPAM', 'SCAM_FRAUD_OR_SPAM'), ('MISINFORMATION', 'MISINFORMATION')], max_length=255, verbose_name='Reason')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default=src.apps.reports.enums.ReportStatus['PENDING'], max_length=255, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(db_column='post_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.posts', verbose_name='Post')),
                ('user', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.users', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='reports_status_e83c1d_idx'), models.Index(fields=['created_at'], name='reports_created_c5f642_idx')],
            },
        ),
    ]
